### ISSUE TITLE
Create Environment Bundle from Directory. 

### ISSUE THREAD

**Issue by rmkennell** [CAAPIM/gateway-developer-plugin#205]
Add ability to create an environment bundle by specifying a directory. Currently, this is achieved by modifying the "environmentProperties" map value in gradle.properties. This is not user friendly with a lot of environment configuration. 

For example, have an environment directory or dev, test, prod, etc

**Comment by amoghsa** [comment]
@rmkennell - We are working on similar idea. We will update public git, once we are ready to launch.

**Comment by amoghsa** [comment]
Released with 1.0
