### ISSUE TITLE
Export without raw.bundle

### ISSUE THREAD

**Issue by maikbaumgartner** [CAAPIM/gateway-developer-plugin#206]
We work with a large gateway that generates a raw.bundle of ~35mb size. Every subproject generates the same raw.bundle of that size, which takes about 11mins per subproject!. So the overall export of our gateway takes about an hour...

It would be nice to have to possibility to either skip the raw.bundle export (in case it's not needed for the folder-structure) or to do it once and duplicate it for the other subprojects.

**Comment by amoghsa** [comment]
@maikbaumgartner - Please make use of [GatewayExportConfig](https://github.com/CAAPIM/gateway-developer-plugin/wiki/Gateway-Export-Plugin#customizing-the-default-plugin-configuration). You can download it once for one folder and reference it afterwards. I will make a note of this for enhancing.

**Comment by maikbaumgartner** [comment]
@amoghsa 
Thank you for your reply. 
Just to make things clear. Is the export-raw bundle actually needed for further processing? Or are the files in the default location "src/main/gateway" sufficient to proceed?

**Comment by amoghsa** [comment]
export-raw is needed as a initial step, that's why it is under build folder. Even if someone runs `gradle clean` after exporting, that is okay. As All policies, services and entities are added under policy and config folder.

You should be able to able to export whole gateway in one project. It is not recommended, but it can be done by using `/` as project folderpath. It should extract everything under root inside src/main/gateway.

It is not recommended as it will bit purpose of using gradle as a backbone for project. You should be able to modularize your projects and create dependency structure, so that your gateway config can be reused with multiple policies / services.

**Comment by maikbaumgartner** [comment]
@amoghsa 
First of all, thank you very much for your support!

> You should be able to able to export whole gateway in one project. It is not recommended, but it can be done by using / as project folderpath. It should extract everything, including child folders, under root inside src/main/gateway.

I rechecked it and I wasn't able to do so. When I set ``folderPath='/'``  in the ``GatewayExportConfig`` it exports only the files in the root dir. No folders/subfolders.

> You can download it once for one folder and reference it afterwards.

Is there any documentation on how to do this? how can I tell a subproject to use the export-raw of the first export? 

Moreover, with gmu it was possible to migrate gateways with granularity of single services, how can this be achieved with the plugin? Define the subprojects as small as possible?

**Comment by amoghsa** [comment]
@maikbaumgartner 
Here is documentation for [beta release](https://github.com/CAAPIM/APIM-Gateway-Developer-Tools#ephemeral-gateway-setup-guide).
Here is documentation for [single-module](https://github.com/CAAPIM/gateway-developer-skeleton-repo/wiki/Configure-Gateway-Skeleton-Repo)
Here is skeleton repo for [multi-module-repo](https://github.com/CAAPIM/ephemeral-gateway-skeleton-repo/tree/Multi-module-ephemeral) - You should be able to copy-paste example folder

**Comment by amoghsa** [comment]
@maikbaumgartner On other hand here is all information regarding multimodule repo with [sample](https://github.com/CAAPIM/gateway-developer-multimodule-skeleton-repo/wiki/Getting-Started-with-the-Multiple-Module-Gateway-Developer-Repository).

**Comment by amoghsa** [comment]
haven't heard, closing issue.
