### ISSUE TITLE
Parameter Order in Policy Templates

### ISSUE THREAD

**Issue by OChristian** [CAAPIM/gateway-developer-plugin#304]
**Describe the bug**
I created an encass to add a Policy template (Value Setter) in the list of policy templates in the portal. The order of the fields are correct when looking at the Encass properties (see screenshot) but after creating the policy bundle and publishing the bundle on Portal 5, the order of the field is displayed in a reverse order (see screenshots). Note that the order is correct in the encass.yml file.

**To Reproduce**
Create a Encass for a Policy Template with two values named ValueA and Value B.
Check that they are correct on the encass properties.
Export using the Gradle plugin.
Create a policy bundle.
Got to Portal 5.
Create the gateway bundle.
Verify that a new Policy Template is added to the list.
Add the Policy template to an API
Expend to see Value A and Value B: in my case, field for Value B appeared before field for Value A

**Expected behavior**
The order for displaying fields should be identical to what is displayed in the Encass Properties.

**Logs**
NA

**Environment (please complete the following information):**
- OS: MacOS for the Gradle Plugin
- Gradle Plugin 1.0.2
- Gateway 10
- Portal 5

**Additional context**
NA
<img width="365" alt="Screenshot 2020-10-14 at 15 48 24" src="https://user-images.githubusercontent.com/11733558/96000260-02544780-0e37-11eb-8ad5-76ddda27bfc8.png">
<img width="339" alt="Screenshot 2020-10-14 at 15 48 12" src="https://user-images.githubusercontent.com/11733558/96000269-03857480-0e37-11eb-949c-6a67087ecbcf.png">
<img width="623" alt="Screenshot 2020-10-14 at 15 47 38" src="https://user-images.githubusercontent.com/11733558/96000276-04b6a180-0e37-11eb-8f69-42045246227e.png">

**Comment by amoghsa** [comment]
Logged internal defect. please check - DE481371
