### ISSUE TITLE
Export is removing annotations

### ISSUE THREAD

**Issue by OChristian** [CAAPIM/gateway-developer-plugin#305]
**Is your feature request related to a problem? Please describe.**
The first time you export an encass from the your developer gateway, there are no annotations. You then add you annotations. Sometime later, you make changes and export again. The annotations you initially added to build the bundle are then removed.

**Describe the solution you'd like**
When exporting, annotations should be preserved if they already exist

**Comment by amoghsa** [comment]
Moving tickets to Rally.
